# Generated by Django 4.2.5 on 2023-10-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='footballplayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Playerid', models.CharField(max_length=15)),
                ('Playername', models.CharField(max_length=30)),
                ('Event', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=20)),
                ('Age', models.IntegerField(max_length=3)),
            ],
        ),
    ]
